fail_fast: false
exclude: ^vendor/.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i]
      - id: clang-tidy
        args: ["--quiet", "--fix-errors"]
        # - id: oclint
        # - id: uncrustify
        # - id: cppcheck
        #   args: ["--enable=all", "--disable=style,unusedFunction", "--check-level=exhaustive", "--language=c", "--inconclusive", "--std=c11", "--suppress=missingIncludeSystem"]
        # - id: cpplint
      # - id: include-what-you-use
