# ==========================================
#   Project Settings
# ==========================================
TARGET_NAME := anukrta
SRC_DIR := src
OBJ_DIR := build
BIN_DIR := build/bin
INC_DIR := include

# Compiler settings
CC := gcc

DEV_FLAGS := -ggdb -Og -Wstrict-prototypes -Wold-style-definition -Wshadow	\
-Wvla -pedantic -Wno-unused-parameter -Wno-unused-variable
# Standard warnings + optimizations + debug info
RELEASE_FLAGS := -O2
CFLAGS := -std=c11 -Wall -Wextra $(DEV_FLAGS)

ASAN := 1

# ==========================================
#   FFmpeg Configuration (No pkg-config)
# ==========================================
# Set the root directory where FFmpeg is installed.
# Common paths: /usr, /usr/local, /opt/ffmpeg
FFMPEG_ROOT := /usr

# Include Flags (Headers)
FFMPEG_INC := -I$(FFMPEG_ROOT)/include

# Linker Flags (Library paths)
# -Wl,-rpath sets the runtime library path so you don't need LD_LIBRARY_PATH
FFMPEG_LIBDIR := -L$(FFMPEG_ROOT)/lib
FFMPEG_RPATH := -Wl,-rpath,$(FFMPEG_ROOT)/lib

# Specific FFmpeg Libraries to link (Add/Remove as needed)
FFMPEG_LIBS := -lavformat -lavcodec -lavutil -lswscale -lswresample

# ==========================================
#   Programmatic File Discovery
# ==========================================
# Find all .c files in SRC_DIR
SOURCES := $(wildcard $(SRC_DIR)/*.c)
# Create object file names (e.g., src/main.c -> obj/main.o)
OBJECTS := $(SOURCES:$(SRC_DIR)/%.c=$(OBJ_DIR)/%.o)
# Dependency files (generated by compiler)
DEPS := $(OBJECTS:.o=.d)

# Combine flags
ALL_CFLAGS := $(CFLAGS) -I$(INC_DIR) $(FFMPEG_INC) -MMD -MP
ALL_LDFLAGS := $(FFMPEG_LIBDIR) $(FFMPEG_RPATH)
ALL_LDLIBS := $(FFMPEG_LIBS) -lm -lpthread -lz


ifeq (${ASAN}, 1)
ASAN_FLAGS := -fsanitize=address,undefined
	ALL_CFLAGS += $(ASAN_FLAGS)
	ALL_LDFLAGS += $(ASAN_FLAGS)
	ASAN_LOG_FILE = asan.log
	ASAN_OPTIONS="log_path=$(ASAN_LOG_FILE)"
endif


# ==========================================
#   Build Rules
# ==========================================

# 1. Main Target
.PHONY: all test bear clean
all: $(BIN_DIR)/$(TARGET_NAME)

# 2. Linking
$(BIN_DIR)/$(TARGET_NAME): $(OBJECTS) | $(BIN_DIR)
	@echo "Linking $(TARGET_NAME)..."
	$(CC) $(ALL_LDFLAGS) $^ $(ALL_LDLIBS) -o $@

# 3. Compiling
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	@echo "Compiling $<..."
	$(CC) $(ALL_CFLAGS) -c $< -o $@

# 4. Directory Creation
$(BIN_DIR) $(OBJ_DIR):
	@mkdir -p $@

# 5. Clean
clean:
	@echo "Cleaning up..."
	@rm -rf $(OBJ_DIR) $(BIN_DIR)

# 6. Include Dependencies
	-include $(DEPS)

bear:
	@echo "Generating compile_database.json"
	bear -- make -B

test:
	@echo "NOT IMPLEMENTED."
