# ==========================================
#   Project Settings
# ==========================================
TARGET_NAME := anukrta
SRC_DIR := src
OBJ_DIR := build/objs
BIN_DIR := build
INC_DIR := include

# Compiler settings
CC := clang

ASAN := 1
DEBUG := 1

# FLAGS FOR DEVELOPMENT
DEV_FLAGS := -ggdb -O0 -g3 -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function \
-fextend-variable-liveness -ftrapv -Wdouble-promotion -Wconversion -Wno-sign-conversion -fno-omit-frame-pointer

# FLAGS FOR RELEASE BUILD
RELEASE_FLAGS := -O2

# DEFAULT FLAGS
CFLAGS := -std=c11 \
-Wall -Wextra -Wstrict-prototypes \
-Wold-style-definition -Wshadow \
-Wvla -pedantic

ifeq (${DEBUG}, 1)
	CFLAGS += $(DEV_FLAGS)
else
	CFLAGS += $(RELEASE_FLAGS)
endif

# ==========================================
#   FFmpeg Configuration (No pkg-config)
# ==========================================
# Set the root directory where FFmpeg is installed.
# Common paths: /usr, /usr/local, /opt/ffmpeg
FFMPEG_ROOT := /usr

# Include Flags (Headers)
FFMPEG_INC := -I$(FFMPEG_ROOT)/include

# Linker Flags (Library paths)
# -Wl,-rpath sets the runtime library path so you don't need LD_LIBRARY_PATH
FFMPEG_LIBDIR := -L$(FFMPEG_ROOT)/lib
FFMPEG_RPATH := -Wl,-rpath,$(FFMPEG_ROOT)/lib

# Specific FFmpeg Libraries to link (Add/Remove as needed)
FFMPEG_LIBS := -lavformat -lavcodec -lavutil -lswscale -lswresample

# ==========================================
#  Address Sanitiser
# ==========================================
# Combine flags
ALL_CFLAGS := $(CFLAGS) -I$(INC_DIR) $(FFMPEG_INC) -MMD -MP
ALL_LDFLAGS := $(FFMPEG_LIBDIR) $(FFMPEG_RPATH)
ALL_LDLIBS := $(FFMPEG_LIBS) -lm -lpthread -lz


ifeq (${ASAN}, 1)
# ASAN Flags
	ASAN_FLAGS := -fsanitize=undefined -fsanitize=address
	ALL_CFLAGS += $(ASAN_FLAGS) -fsanitize-trap
	ALL_LDFLAGS += $(ASAN_FLAGS)

# Name of ASAN logfile
	ASAN_LOG_FILE := etc/asan.log

# Default options
	DEFAULT_ASAN_OPTIONS = abort_on_error=1:halt_on_error=1:log_path=$(ASAN_LOG_FILE)
	DEFAULT_UBSAN_OPTIONS = abort_on_error=1:halt_on_error=1:print_stacktrace=1
endif

# ==========================================
#   Programmatic File Discovery
# ==========================================
# Find all .c files in SRC_DIR
SOURCES := $(wildcard $(SRC_DIR)/*.c)
# Create object file names (e.g., src/main.c -> obj/main.o)
OBJECTS := $(SOURCES:$(SRC_DIR)/%.c=$(OBJ_DIR)/%.o)
# Dependency files (generated by compiler)
DEPS := $(OBJECTS:.o=.d)

# ==========================================
#   Build Rules
# ==========================================

# 1. Main Target
.PHONY: all test run bear clean
all: $(BIN_DIR)/$(TARGET_NAME)

# 2. Linking
$(BIN_DIR)/$(TARGET_NAME): $(OBJECTS) | $(BIN_DIR)
	@echo "=================================================="
	@echo "Linking $(TARGET_NAME)..."
	$(CC) $(ALL_LDFLAGS) $^ $(ALL_LDLIBS) -o $@

# 3. Compiling
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	@echo "Compiling $<..."
	$(CC) $(ALL_CFLAGS) -c $< -o $@

# 4. Directory Creation
$(BIN_DIR) $(OBJ_DIR):
	@mkdir -p $@

# 5. Clean
clean:
	@echo "Cleaning up..."
	@rm -rf $(OBJ_DIR) $(BIN_DIR)
	@rm -f etc/asan.log.*

# 6. Include Dependencies
# -include $(DEPS)

compile_commands.json: clean
	@echo "Generating compile_commands.json..."
	bear -- $(MAKE) all

# Alias for convenience
bear: compile_commands.json


test: $(BIN_DIR)/$(TARGET_NAME)
	@echo "=================================================="
	@echo "Running $(TARGET_NAME) with Sanitizers..."
ifeq (${ASAN}, 1)
	@echo "ASAN Options: $(DEFAULT_ASAN_OPTIONS)"
	@echo "Logs will be written to: $(ASAN_LOG_FILE).<pid>"
endif
	@echo "=================================================="
	@ASAN_OPTIONS="$(DEFAULT_ASAN_OPTIONS):$(ASAN_OPTIONS)" \
	 UBSAN_OPTIONS="$(DEFAULT_UBSAN_OPTIONS):$(UBSAN_OPTIONS)" \
	 ./$(BIN_DIR)/$(TARGET_NAME)

run: test
