MAKEFLAGS += --no-print-directory

USE_MOLD ?= 1
VARIANT ?= debug
SANITIZER ?= none
DEBUG ?= 1

LDFLAGS ?=

ifeq ($(USE_MOLD), 1)
	LDFLAGS += -fuse-ld=mold
endif

include config.mk

# ==========================================
#   Project Settings
# ==========================================
TARGET_NAME := anukrta
TEST_TARGET_NAME := test

SRC_DIR := src
BUILD_ROOT := build
BUILD_DIR := $(BUILD_ROOT)/$(VARIANT)
OBJ_DIR := $(BUILD_DIR)/objs
INCLUDE_DIR := src
VENDOR_DIR := vendor
TEST_DIR := tests

# DEFAULT C FLAGS
CFLAGS := -std=gnu23 \
-Wall -Wextra \
-Wstrict-prototypes -Wmissing-prototypes \
-Wshadow -Wvla \
-Wconversion -Wsign-conversion -Wdouble-promotion \
-Wmissing-include-dirs \
-Wnested-externs \
-Wredundant-decls -Wold-style-definition \
-Wunused-function -Wunused-parameter -Wunused-variable -Wmissing-prototypes \
-Wjump-misses-init -Wuninitialized -Warray-parameter -Winit-self -Wundef
# -Wpadded

# Release or Profile
ifneq ($(filter profile release,$(VARIANT)),)
	PREPROC_DEFS += -DNDEBUG
	LDFLAGS += $(COMPILER_RELEASE_LDFLAGS)

	ifeq ($(VARIANT), release)
		CFLAGS += $(RELEASE_FLAGS)
	else ifeq ($(VARIANT), profile)
		CFLAGS += $(PROFILE_FLAGS)
	endif
endif

# Inject Compiler-specific flags from config.mk
CFLAGS += $(COMPILER_CFLAGS)
LDFLAGS += $(COMPILER_LDFLAGS)

# Development build
ifeq ($(DEBUG), 1)
	CFLAGS += $(DEV_FLAGS)
else
	CFLAGS += $(RELEASE_FLAGS)
endif

# Profiling build
ifeq ($(PROFILE), 1)
	CFLAGS += $(PROFILE_FLAGS)
endif

# Release or profile
ifneq (,$(filter 1,$(PROFILE) $(RELEASE)))
	PREPROC_DEFS += -DNDEBUG
endif

INCLUDES = $(addprefix -I,$(VENDOR_DIR) $(SRC_DIR))
CPPFLAGS = $(INCLUDES) -MMD -MP $(PREPROC_DEFS)

# ==========================================
#   FFmpeg Configuration
# ==========================================
# FFmpeg libraries to link against
FFMPEG_CFLAGS := $(shell pkg-config --cflags libavdevice libavfilter libavformat libavcodec libswresample libswscale libavutil)
FFMPEG_LIBS := $(shell pkg-config --libs libavdevice libavfilter libavformat libavcodec libswresample libswscale libavutil)

CFLAGS += $(FFMPEG_CFLAGS)
LDFLAGS += -Wl,--as-needed
LDLIBS := $(FFMPEG_LIBS) -lm -lpthread

# ==========================================
# Sanitisers
# ==========================================
SAN_FLAGS :=

ifeq ($(SANITIZER), asan)
	CFLAGS += -fno-optimize-sibling-calls
	SAN_FLAGS := -fsanitize=address,undefined,unreachable -fsanitize-address-use-after-scope
else ifeq ($(SANITIZER), tsan)
	SAN_FLAGS := -fsanitize=thread,undefined,unreachable
endif

ifneq ($(filter asan tsan, $(SANITIZER)),)
# Add Clang's extra sanitizers if using Clang
	ifeq ($(CC), clang)
		SAN_FLAGS += $(CLANG_EXTRA_SANS)
	endif

	CFLAGS += $(SAN_FLAGS) -fno-omit-frame-pointer
	LDFLAGS += $(SAN_FLAGS)
# Runtime Options
	ASAN_LOG_FILE := etc/asan.log
	DEFAULT_ASAN_OPTIONS := detect_leaks=1:abort_on_error=1:halt_on_error=1:log_path=$(ASAN_LOG_FILE):strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1
	DEFAULT_LSAN_OPTIONS := log_threads=1
	DEFAULT_UBSAN_OPTIONS := abort_on_error=1:halt_on_error=1:print_stacktrace=1
	DEFAULT_TSAN_OPTIONS := enable_adaptive_delay=1:adaptive_delay_aggressiveness=50:halt_on_error=1
endif

# ==========================================
#   Vendor Compilation Flags
# ==========================================
# We want vendor code to be optimised + no warnings + no debugging
VENDOR_CFLAGS := -O3 -g -w -DNDEBUG $(COMPILER_CFLAGS)

# Inherit sanitizers if they are active
ifneq ($(filter asan tsan, $(SANITIZER)),)
	VENDOR_CFLAGS += $(SAN_FLAGS) -fno-omit-frame-pointer
endif

# ==========================================
#   Programmatic File Discovery
# ==========================================

SRC_SOURCES := $(shell find $(SRC_DIR) -name '*.c')
TEST_SOURCES := $(shell find $(TEST_DIR) -name '*.c' 2>/dev/null)
VENDOR_SOURCES := $(wildcard $(VENDOR_DIR)/*.c)

SOURCES := $(SRC_SOURCES) $(VENDOR_SOURCES)

# Create object file names (src/main.c -> obj/main.o)
SRC_OBJECTS    := $(SRC_SOURCES:%.c=$(OBJ_DIR)/%.o)
VENDOR_OBJECTS := $(VENDOR_SOURCES:%.c=$(OBJ_DIR)/%.o)
TEST_OBJECTS := $(TEST_SOURCES:%.c=$(OBJ_DIR)/%.o)

OBJECTS := $(SRC_OBJECTS) $(VENDOR_OBJECTS)

# Helper to remove main.o from the library link for tests
MAIN_OBJ := $(OBJ_DIR)/$(SRC_DIR)/main.o
LIB_OBJECTS := $(filter-out $(MAIN_OBJ), $(OBJECTS))

# Dependency files (generated by compiler)
DEPS := $(OBJECTS:.o=.d) $(TEST_OBJECTS:.o=.d)

FILES := $(shell find $(SRC_DIR) $(TEST_DIR) -name '*.[ch]' -o -name '*.inl' 2>/dev/null)

# ==========================================
#   Build Rules
# ==========================================

# Skip building tests when refactoring etc
SKIP_TESTS ?= 0
# Determine which targets to build
TARGETS_TO_BUILD := $(BUILD_DIR)/$(TARGET_NAME)

# Skip building tests for sanitizer builds
ifeq ($(SANITIZER), none)
	ifneq ($(SKIP_TESTS), 1)
		TARGETS_TO_BUILD += $(BUILD_DIR)/$(TEST_TARGET_NAME)
	endif
endif

.PHONY: all run clean test run lint check release release-debug debug format memcheck analyze

.DEFAULT_GOAL := debug

# ALL
all: debug asan tsan profile release

asan:
	@echo "=== Building ASAN (Address + UBSAN) Variant ==="
	$(Q)$(MAKE) -s VARIANT=asan SANITIZER=asan DEBUG=1 build-variant 2>/dev/null

tsan:
	@echo "=== Building TSAN (Thread + UBSAN) Variant ==="
	$(Q)$(MAKE) -s VARIANT=tsan SANITIZER=tsan DEBUG=1 build-variant 2>/dev/null

debug:
	@echo "=== Building Default Debug Variant ==="
	$(Q)$(MAKE) VARIANT=debug SANITIZER=$(SANITIZER) DEBUG=1 build-variant

profile:
	@echo "=== Building Profile Variant ==="
	$(Q)$(MAKE) VARIANT=profile SANITIZER=$(SANITIZER) DEBUG=0 build-variant 2>/dev/null

release:
	@echo "=== Building Release Variant ==="
	$(Q)$(MAKE) VARIANT=release SANITIZER=$(SANITIZER) DEBUG=0 build-variant 2>/dev/null

build-variant: $(TARGETS_TO_BUILD)

$(BUILD_DIR)/$(TARGET_NAME): $(OBJECTS)
	@mkdir -p $(dir $@)
	$(ECHO_V) "Linking $(VARIANT) -> $(TARGET_NAME)..."
	$(Q)$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@

$(BUILD_DIR)/$(TEST_TARGET_NAME): $(LIB_OBJECTS) $(TEST_OBJECTS)
	@mkdir -p $(dir $@)
	$(ECHO_V) "Linking $(VARIANT) -> $(TEST_TARGET_NAME)..."
	$(Q)$(CC) $(LDFLAGS) $^ $(LDLIBS) -lcriterion -o $@

$(OBJ_DIR)/$(VENDOR_DIR)/%.o: $(VENDOR_DIR)/%.c
	@mkdir -p $(dir $@)
	$(ECHO_V) "Compiling Vendor [optimized] $<..."
	$(Q)$(CC) $(VENDOR_CFLAGS) $(CPPFLAGS) -c $< -o $@

$(OBJ_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(ECHO_V) "Compiling [$(VARIANT)] $<..."
	$(Q)$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

.PHONY: run test run-asan test-asan run-tsan test-tsan

# Helpers so we don't have to type out variable names to test specific builds
run-asan:  ; $(MAKE) VARIANT=asan SANITIZER=asan run
run-tsan:  ; $(MAKE) VARIANT=tsan SANITIZER=tsan run

run: build-variant
ifneq ($(filter asan tsan, $(SANITIZER)),)
	@echo '--- Running $(TARGET_NAME) [$(SANITIZER)] ---'
	@env ASAN_OPTIONS="$(DEFAULT_ASAN_OPTIONS):$(ASAN_OPTIONS)" \
		LSAN_OPTIONS="$(DEFAULT_LSAN_OPTIONS):$(LSAN_OPTIONS)" \
		UBSAN_OPTIONS="$(DEFAULT_UBSAN_OPTIONS):$(UBSAN_OPTIONS)" \
		TSAN_OPTIONS="$(DEFAULT_TSAN_OPTIONS):$(TSAN_OPTIONS)" \
		./$(BUILD_DIR)/$(TARGET_NAME)
else
	@echo '--- Running $(TARGET_NAME) [$(VARIANT)] ---'
	@./$(BUILD_DIR)/$(TARGET_NAME)
endif

test: build-variant
	@echo "--- Testing [$(VARIANT)] ---"
	./$(BUILD_DIR)/$(TEST_TARGET_NAME) -j$(shell nproc)

.PHONY: clean bear analyze check format lint memcheck
# Clean
clean:
	@echo "Cleaning up all build variants..."
	@rm -rf $(BUILD_ROOT)
	@rm -f etc/asan.log.*

clean-debug:
	@echo "Cleaning up debug build..."
	@rm -rf $(BUILD_ROOT)/debug

bear:
	@mkdir -p $(BUILD_ROOT)/debug
	@echo "Generating compile_commands.json..."
	$(Q)bear -- $(MAKE) -B CC=clang debug

analyze: clean-debug
	@scan-build --force-analyze-debug-code -analyze-headers --exclude ./$(VENDOR_DIR) -o $(BUILD_DIR)/scan-reports $(MAKE)

cppcheck:
	@cppcheck -q --enable=all --disable=style,unusedFunction --check-level=exhaustive --language=c --inconclusive --std=c11 \
	--suppress=missingIncludeSystem \
	--template='{file}:{line}:{column}: {severity}: {message} [{id}]' \
	-I $(VENDOR_DIR) -i $(VENDOR_DIR) $(SRC_DIR)

format:
	@find $(SRC_DIR) $(TEST_DIR) -name '*.[ch]' -o -name '*.inl' 2>/dev/null | xargs -P $(shell nproc) clang-format -i --verbose

lint:
	@run-clang-tidy -quiet -hide-progress -config-file .clang-tidy -fix -j $(shell nproc) -format -source-filter '^src/*'

memcheck: debug
	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./$(BUILD_ROOT)/debug/$(TARGET_NAME)

print-%: ; @echo $*=$($*)

# Include Dependencies
-include $(DEPS)
